export default {

	REFERENCES_LOAD_SUCCESS: 'REFERENCES_LOAD_SUCCESS',
	REFERENCES_LOAD_FAIL:    'REFERENCES_LOAD_FAIL',
	RECIPES_LOAD_SUCCESS:    'RECIPES_LOAD_SUCCESS',
	RECIPES_LOAD_FAIL:       'RECIPES_LOAD_FAIL',
	RECIPES_LOADING:         'RECIPES_LOADING',
	LOAD_STATUS_IN_PROCESS:  1,
	LOAD_STATUS_FINISHED:    0,
	LOAD_STATUS_ERROR:       2
}